const goats = [
  {
    id: 'goat1',
    name: 'Billy',
    disposition: 'rude',
    imageUrl: 'https://live.staticflickr.com/99/291672307_be77b1c307_b.jpg',
    fullness: 67,
    favPose: 'Downward Facing Dog',
    isFainting: true,
    color: 'white and black',
  },
  {
    id: 'goat2',
    name: 'Greg',
    disposition: 'peaceful',
    imageUrl: 'https://images.fineartamerica.com/images/artworkimages/mediumlarge/1/billy-goat-michelle-sherwood.jpg',
    fullness: 30,
    favPose: 'Shavasana',
    isFainting: false,
    color: 'white',
  },
  {
    id: 'goat3',
    name: 'Beatrice',
    disposition: 'sassy',
    imageUrl: 'https://images2.minutemediacdn.com/image/upload/c_crop,h_843,w_1500,x_0,y_10/f_auto,q_auto,w_1100/v1555172614/shape/mentalfloss/iStock-177369626_1.jpg',
    fullness: 6,
    favPose: 'Balasana',
    isFainting: true,
    color: 'white',
  },
  {
    id: 'goat4',
    name: 'George',
    disposition: 'inquisitive',
    imageUrl: 'https://cdn.vox-cdn.com/thumbor/QuO4OXij6CKiWk49qmSxBz4RHE0=/0x79:1200x925/1200x800/filters:focal(540x268:732x460)/cdn.vox-cdn.com/uploads/chorus_image/image/61759449/cool_goat_2.0.jpg',
    fullness: 7,
    favPose: 'Halasana',
    isFainting: false,
    color: 'white and black',
  },
  {
    id: 'goat5',
    name: 'Satan',
    disposition: 'somber',
    imageUrl: 'http://1l0rn41qj2vl21scq19b0c71-wpengine.netdna-ssl.com/wp-content/uploads/2017/10/oldenglish_1.jpg',
    fullness: 66,
    favPose: 'Karnapidasana',
    isFainting: false,
    color: 'black',
  },
  {
    id: 'goat6',
    name: 'Shelley',
    disposition: 'hateful',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/b/b2/Hausziege_04.jpg',
    fullness: 55,
    favPose: 'Karnapidasana',
    isFainting: true,
    color: 'brown',
  },
];

export default goats;
